#数据源基础信息
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://111.111.111.111:3306/hodor?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false
    username: hodor_adm
    password: 888888888
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM t_pub_param
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000\
  redis:
    host: xxx.xxx.xxx.xxx
    port: 8998
    database: 0
    password: 11111111
    timeout: 3000


#服务相关参数
server:
  port: 8089

#日志参数
log:
#  path: /Users/bpascal/Downloads/log
logging:
  level:
    root: INFO
    com.codido.needle.core.mapper: debug
#mybatis基础配置
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

#微信参数
wechat:
  app:
    appId: wx209e789aebc1fd6e
    secret: 111111111111111111111111111111
    token: 111111
    aesKey: 111111
  pay:
    appId: wxb0df5ef1b490a8b1
    mchId: 1111111111
    mchKey: 111111111111111111111111111111
    keyPath: /home/serveradm/apiclient_cert.p12

#服务路径相关
basecontext:
  urlpath:
    requestpath: http://www.rivendell.top

#七牛云存储参数
qiniu:
  userparams:
    accesskey: yAC2iK-zdCfoo-4RttvC9rmKi98TwVXtfvu6EQHl
    secretkey: 1111111111111111111111111111111111111111
    imagebucket: bpascal
    filecontext: http://images.rivendell.top/