#数据源基础信息
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://rm-wz9x0nh16mdb2e58q.mysql.rds.aliyuncs.com:3306/lottostore_ptc?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false
        username: 111111
        password: 111111
        driverClassName: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM t_pub_param
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000\

#服务参数
server:
    port: 9011

#日志参数
log:
    path: /home/serveradm/logs

#微信参数
wechat:
    mp:
        appId: 111111
        secret: 111111
        token: 111111
        aesKey: 111111
    jiqibaba:
        appId: 111111
        secret: 111111
        token: 111111
        aesKey: 111111
    pay:
        appId: 111111
        mchId: 111111
        mchKey: 111111
        keyPath: /home/serveradm/apiclient_cert.p12
    zdjl:
        appId: 111111
        secret: 111111
        token: 111111
        aesKey: 111111

##服务商模式下的子商户公众账号ID
#subAppId=
##服务商模式下的子商户号
#subMchId=

#服务路径相关
basecontext:
    urlpath:
        requestpath: https://m.caishiduo.com
        zdjlrequestpath: https://m.zdjl.caishiduo.com
    filepath:
        picsavepath: /home/webadm/webroot/resources/images/
        picrequestpath: https://m.caishiduo.com/resources/images/
    serverpath:
        serverip: 112.74.163.242
        notifycontext: https://m.caishiduo.com/backapi

#中大奖了机器人后台服务上下文
robotbasecontext:
    urlpath:
        transorderpath: http://112.65.144.19:8083

#七牛云存储参数
qiniu:
    userparams:
        accesskey: 111111
        secretkey: 111111
        imagebucket: 111111
        filecontext: http://p5tzl8eml.bkt.clouddn.com/