#数据源基础信息
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/lotto_sit?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false
        username: jbadm
        password: 111111
        driverClassName: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM t_pub_param
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000\

#服务参数
server:
    port: 8080

#日志参数
log:
    path: /home/serveradm/logs

#微信参数
wechat:
    mp:
        appId: 111111
        secret: 111111
        token: 111111
        aesKey: 111111
    jiqibaba:
        appId: wxb0df5ef1b490a8b1
        secret: eefe01bbd4c9ba76b152b321f81a5349
        token: nUllk8ZtI3
        aesKey: FegO6XA3vOLIQ3o2AOy7UrrsupMtTj2p3d6CTlGkQME
    pay:
        appId: wxb0df5ef1b490a8b1
        mchId: 1482967462
        mchKey: pKtgKaJ4xDmrXK9xauB84b4JgQ7PuxOA
        keyPath: /home/serveradm/apiclient_cert.p12
    zdjl:
        appId: wx79a7b61a9eafe577
        secret: f81c57067f1a188bd0d187682bb7e6b0
        token: cMIroThFEw8n9viH
        aesKey: AIDriEIpyyzAEod9PH89hiYI7rxJkIPxpIPO4GkFrNK
    planet:
        appId: wxfb7b7403bdf41a99
        secret: 9271bdabc09fa3ac9fbfde17ea0112e8
        token: ocHyvVz478IEDnmT
        aesKey: 9ZcMkExRXCOYDsXX55fDpNmodTmuV7SXz36N4z3ccVc

##服务商模式下的子商户公众账号ID
#subAppId=
##服务商模式下的子商户号
#subMchId=

#服务路径相关
basecontext:
    urlpath:
        requestpath: http://mt.caishiduo.com
        zdjlrequestpath: http://mt.zdjl.caishiduo.com
    filepath:
        picsavepath: /home/webadm/webroot/resources/images/
        picrequestpath: http://mt.jiqibaba.com/resources/images/
    serverpath:
        serverip: 47.92.24.144
        notifycontext: http://mt.caishiduo.com/backapi

#中大奖了机器人后台服务上下文
robotbasecontext:
    urlpath:
        transorderpath: http://112.65.144.19:8083

#七牛云存储参数
qiniu:
    userparams:
        accesskey: yAC2iK-zdCfoo-4RttvC9rmKi98TwVXtfvu6EQHl
        secretkey: f0JjZtkq77zoxXaneP2E7xcKPLKWNKALnlaUHFj5
        imagebucket: caishiduo
        filecontext: http://p5tzl8eml.bkt.clouddn.com/