#数据源基础信息
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://111.111.111.111:3306/hodor?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false
    username: hodor_adm
    password: 888888888
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM t_pub_param
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000\
  redis:
    host: 127.0.0.1
    port: 8998
    database: 0
    password: ddR7uO8a
    timeout: 3000

#服务参数
server:
  port: 8089

#日志参数
log:
  path: /home/serveradm/logs

#mybatis基础配置
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

#微信参数
wx:
  mp:
    appId: wx6c88e29c7c621f1f
    secret: 4bfdce612906f8eff8e738cf642918b0
    token: LongLiveJB2099
    aesKey: Xdku2WTJWpyo05qiOmnbqRRWMUvMxsKwZJmDsIbCgu4

#服务路径相关
basecontext:
  urlpath:
    requestpath: http://mt.caishiduo.com
    zdjlrequestpath: http://mt.zdjl.caishiduo.com
  filepath:
    picsavepath: /home/webadm/webroot/resources/images/
    picrequestpath: http://mt.jiqibaba.com/resources/images/
  serverpath:
    serverip: 47.92.24.144
    notifycontext: http://mt.caishiduo.com/backapi
  mallpath:
    mallbasepath: https://mt.jiqibaba.com/mall/


#七牛云存储参数
qiniu:
  userparams:
    accesskey: yAC2iK-zdCfoo-4RttvC9rmKi98TwVXtfvu6EQHl
    secretkey: f0JjZtkq77zoxXaneP2E7xcKPLKWNKALnlaUHFj5
    imagebucket: caishiduo
    filecontext: http://p5tzl8eml.bkt.clouddn.com/