package com.codido.hodor.mapper;

import com.codido.hodor.model.OrdOrder;
import com.codido.hodor.model.OrdOrderExample;
import com.codido.hodor.model.OrdOrderOP;
import com.codido.hodor.model.UsrMsg;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.Date;
import java.util.List;

public interface OrdOrderOPMapper {


    @Select({
            "select",
            "ORDER_ID, ORDER_NO, LOTTO_INST_ID, INIT_USER_ID, DEAL_USER_ID, DEAL_SHOP_ID, ",
            "BET_TIMES, ORDER_TOTAL_BETS_COUNT, ORDER_PRICE, ORDER_STS, COM_GAME_STYLE,TICKET_UPLOAD_STS, ",
            "BONUS_STS, BONUS_AMT, BONUS_DESC,BONUS_PAY_ORDER_NO, ORDER_CREATE_TIME, ORDER_CANCEL_TIME, ORDER_SEND_TIME, ",
            "ORDER_ACCEPT_TIME, ORDER_TICKET_PIC, SUBMIT_FORM_ID, ORDER_PUSHMSG_STS, TICKET_UPLOAD_TIME, ",
            "PAY_ORDER_ID, PAY_CHANNEL, PAY_STS, ORDER_PAY_TIME, ORDER_REJECT_TIME,ORDER_SOURCE, CHASE_NO, ",
            "COP_ORDER_NO, RECIVE_BONUS_TIME, RECIVE_BONUS_STS_TIME, APPLY_BONUS_TIME, FINISH_BONUS_TIME,",
            "ORDER_TICKET_RECIVE_STS, ORDER_TICKET_RECIVE_TIME,ORDER_CHANNEL ",
            "from t_ord_order",
            "where ORDER_ID = #{orderId,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
            @Arg(column="ORDER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
            @Arg(column="ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="LOTTO_INST_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="INIT_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_SHOP_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BET_TIMES", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_TOTAL_BETS_COUNT", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_PRICE", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="COM_GAME_STYLE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="TICKET_UPLOAD_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_AMT", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BONUS_DESC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="BONUS_PAY_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_CREATE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CANCEL_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SEND_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_ACCEPT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_PIC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="SUBMIT_FORM_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_PUSHMSG_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="TICKET_UPLOAD_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="PAY_ORDER_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="PAY_CHANNEL", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="PAY_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_PAY_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_REJECT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SOURCE", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="CHASE_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="COP_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="RECIVE_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="RECIVE_BONUS_STS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="APPLY_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="FINISH_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_RECIVE_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_TICKET_RECIVE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CHANNEL", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    OrdOrderOP selectByPrimaryKey(Long orderId);

    @Select({
            "select",
            "ORDER_ID, ORDER_NO, LOTTO_INST_ID, INIT_USER_ID, DEAL_USER_ID, DEAL_SHOP_ID, ",
            "BET_TIMES, ORDER_TOTAL_BETS_COUNT, ORDER_PRICE, ORDER_STS,COM_GAME_STYLE, TICKET_UPLOAD_STS, ",
            "BONUS_STS, BONUS_AMT, BONUS_DESC,BONUS_PAY_ORDER_NO, ORDER_CREATE_TIME, ORDER_CANCEL_TIME, ORDER_SEND_TIME, ",
            "ORDER_ACCEPT_TIME, ORDER_TICKET_PIC, SUBMIT_FORM_ID, ORDER_PUSHMSG_STS, TICKET_UPLOAD_TIME, ",
            "PAY_ORDER_ID, PAY_CHANNEL, PAY_STS, ORDER_PAY_TIME, ORDER_REJECT_TIME,ORDER_SOURCE, CHASE_NO, ",
            "COP_ORDER_NO, RECIVE_BONUS_TIME, RECIVE_BONUS_STS_TIME, APPLY_BONUS_TIME, FINISH_BONUS_TIME,",
            "ORDER_TICKET_RECIVE_STS, ORDER_TICKET_RECIVE_TIME,ORDER_CHANNEL ",
            "from t_ord_order",
            "where ORDER_NO = #{orderNo,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
            @Arg(column="ORDER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
            @Arg(column="ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="LOTTO_INST_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="INIT_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_SHOP_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BET_TIMES", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_TOTAL_BETS_COUNT", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_PRICE", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="COM_GAME_STYLE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="TICKET_UPLOAD_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_AMT", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BONUS_DESC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="BONUS_PAY_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_CREATE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CANCEL_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SEND_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_ACCEPT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_PIC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="SUBMIT_FORM_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_PUSHMSG_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="TICKET_UPLOAD_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="PAY_ORDER_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="PAY_CHANNEL", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="PAY_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_PAY_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_REJECT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SOURCE", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="CHASE_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="COP_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="RECIVE_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="RECIVE_BONUS_STS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="APPLY_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="FINISH_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_RECIVE_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_TICKET_RECIVE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CHANNEL", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    OrdOrderOP selectByOrderNo(@Param("orderNo")String orderNo);

    @Select({
            "select",
            "ORDER_ID, ORDER_NO, LOTTO_INST_ID, INIT_USER_ID, DEAL_USER_ID, DEAL_SHOP_ID, ",
            "BET_TIMES, ORDER_TOTAL_BETS_COUNT, ORDER_PRICE, ORDER_STS,COM_GAME_STYLE, TICKET_UPLOAD_STS, ",
            "BONUS_STS, BONUS_AMT, BONUS_DESC,BONUS_PAY_ORDER_NO, ORDER_CREATE_TIME, ORDER_CANCEL_TIME, ORDER_SEND_TIME, ",
            "ORDER_ACCEPT_TIME, ORDER_TICKET_PIC, SUBMIT_FORM_ID, ORDER_PUSHMSG_STS, TICKET_UPLOAD_TIME, ",
            "PAY_ORDER_ID, PAY_CHANNEL, PAY_STS, ORDER_PAY_TIME, ORDER_REJECT_TIME,ORDER_SOURCE, CHASE_NO, ",
            "COP_ORDER_NO, RECIVE_BONUS_TIME, RECIVE_BONUS_STS_TIME, APPLY_BONUS_TIME, FINISH_BONUS_TIME,",
            "ORDER_TICKET_RECIVE_STS, ORDER_TICKET_RECIVE_TIME,ORDER_CHANNEL ",
            "from t_ord_order",
            "where BONUS_PAY_ORDER_NO = #{bonusOrderNo,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
            @Arg(column="ORDER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
            @Arg(column="ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="LOTTO_INST_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="INIT_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_SHOP_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BET_TIMES", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_TOTAL_BETS_COUNT", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_PRICE", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="COM_GAME_STYLE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="TICKET_UPLOAD_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_AMT", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BONUS_DESC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="BONUS_PAY_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_CREATE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CANCEL_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SEND_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_ACCEPT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_PIC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="SUBMIT_FORM_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_PUSHMSG_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="TICKET_UPLOAD_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="PAY_ORDER_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="PAY_CHANNEL", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="PAY_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_PAY_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_REJECT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SOURCE", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="CHASE_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="COP_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="RECIVE_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="RECIVE_BONUS_STS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="APPLY_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="FINISH_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_RECIVE_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_TICKET_RECIVE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CHANNEL", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    OrdOrderOP selectByBonusOrderNo(@Param("bonusOrderNo")String orderNo);

    @Update({
            "update t_ord_order",
            "set ORDER_NO = #{orderNo,jdbcType=VARCHAR},",
            "LOTTO_INST_ID = #{lottoInstId,jdbcType=BIGINT},",
            "INIT_USER_ID = #{initUserId,jdbcType=BIGINT},",
            "DEAL_USER_ID = #{dealUserId,jdbcType=BIGINT},",
            "DEAL_SHOP_ID = #{dealShopId,jdbcType=BIGINT},",
            "BET_TIMES = #{betTimes,jdbcType=INTEGER},",
            "ORDER_TOTAL_BETS_COUNT = #{orderTotalBetsCount,jdbcType=INTEGER},",
            "ORDER_PRICE = #{orderPrice,jdbcType=INTEGER},",
            "ORDER_STS = #{orderSts,jdbcType=CHAR},",
            "COM_GAME_STYLE = #{comGameStyle,jdbcType=VARCHAR},",
            "TICKET_UPLOAD_STS = #{ticketUploadSts,jdbcType=CHAR},",
            "BONUS_STS = #{bonusSts,jdbcType=CHAR},",
            "BONUS_AMT = #{bonusAmt,jdbcType=BIGINT},",
            "BONUS_DESC = #{bonusDesc,jdbcType=VARCHAR},",
            "BONUS_PAY_ORDER_NO = #{bonusPayOrderNo,jdbcType=VARCHAR},",
            "ORDER_CREATE_TIME = #{orderCreateTime,jdbcType=TIMESTAMP},",
            "ORDER_CANCEL_TIME = #{orderCancelTime,jdbcType=TIMESTAMP},",
            "ORDER_SEND_TIME = #{orderSendTime,jdbcType=TIMESTAMP},",
            "ORDER_ACCEPT_TIME = #{orderAcceptTime,jdbcType=TIMESTAMP},",
            "ORDER_TICKET_PIC = #{orderTicketPic,jdbcType=VARCHAR},",
            "SUBMIT_FORM_ID = #{submitFormId,jdbcType=VARCHAR},",
            "ORDER_PUSHMSG_STS = #{orderPushmsgSts,jdbcType=CHAR},",
            "TICKET_UPLOAD_TIME = #{ticketUploadTime,jdbcType=TIMESTAMP},",
            "PAY_ORDER_ID = #{payOrderId,jdbcType=VARCHAR},",
            "PAY_CHANNEL = #{payChannel,jdbcType=CHAR},",
            "PAY_STS = #{paySts,jdbcType=CHAR},",
            "ORDER_PAY_TIME = #{orderPayTime,jdbcType=TIMESTAMP},",
            "ORDER_REJECT_TIME = #{orderRejectTime,jdbcType=TIMESTAMP},",
            "ORDER_SOURCE = #{orderSource,jdbcType=CHAR},",
            "CHASE_NO = #{chaseNo,jdbcType=VARCHAR},",
            "COP_ORDER_NO = #{copOrderNo,jdbcType=VARCHAR},",
            "RECIVE_BONUS_TIME = #{reciveBonusTime,jdbcType=TIMESTAMP},",
            "RECIVE_BONUS_STS_TIME = #{reciveBonusStsTime,jdbcType=TIMESTAMP},",
            "APPLY_BONUS_TIME = #{applyBonusTime,jdbcType=TIMESTAMP},",
            "FINISH_BONUS_TIME = #{finishBonusTime,jdbcType=TIMESTAMP},",
            "ORDER_TICKET_RECIVE_STS = #{orderTicketReciveSts,jdbcType=CHAR},",
            "ORDER_TICKET_RECIVE_TIME = #{orderTicketReciveTime,jdbcType=TIMESTAMP},",
            "ORDER_CHANNEL = #{orderChannel,jdbcType=VARCHAR}",
            "where ORDER_ID = #{orderId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(OrdOrderOP record);

    @Select({
            "select",
            "ORDER_ID, ORDER_NO, LOTTO_INST_ID, INIT_USER_ID, DEAL_USER_ID, DEAL_SHOP_ID, ",
            "BET_TIMES, ORDER_TOTAL_BETS_COUNT, ORDER_PRICE, ORDER_STS,COM_GAME_STYLE, TICKET_UPLOAD_STS, ",
            "BONUS_STS, BONUS_AMT, BONUS_DESC,BONUS_PAY_ORDER_NO, ORDER_CREATE_TIME, ORDER_CANCEL_TIME, ORDER_SEND_TIME, ",
            "ORDER_ACCEPT_TIME, ORDER_TICKET_PIC, SUBMIT_FORM_ID, ORDER_PUSHMSG_STS, TICKET_UPLOAD_TIME, ",
            "PAY_ORDER_ID, PAY_CHANNEL, PAY_STS, ORDER_PAY_TIME,ORDER_REJECT_TIME, ORDER_SOURCE, CHASE_NO, ",
            "COP_ORDER_NO, RECIVE_BONUS_TIME, RECIVE_BONUS_STS_TIME, APPLY_BONUS_TIME, FINISH_BONUS_TIME,",
            "ORDER_TICKET_RECIVE_STS, ORDER_TICKET_RECIVE_TIME,ORDER_CHANNEL ",
            "from t_ord_order",
            "where INIT_USER_ID = #{initUserId,jdbcType=BIGINT} AND DEAL_SHOP_ID IS NOT NULL",
            "order by ORDER_CREATE_TIME desc",
            "LIMIT  #{pageNo,jdbcType=BIGINT},#{prePageCount,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
            @Arg(column="ORDER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
            @Arg(column="ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="LOTTO_INST_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="INIT_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_SHOP_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BET_TIMES", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_TOTAL_BETS_COUNT", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_PRICE", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="COM_GAME_STYLE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="TICKET_UPLOAD_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_AMT", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BONUS_DESC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="BONUS_PAY_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_CREATE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CANCEL_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SEND_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_ACCEPT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_PIC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="SUBMIT_FORM_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_PUSHMSG_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="TICKET_UPLOAD_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="PAY_ORDER_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="PAY_CHANNEL", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="PAY_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_PAY_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_REJECT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SOURCE", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="CHASE_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="COP_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="RECIVE_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="RECIVE_BONUS_STS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="APPLY_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="FINISH_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_RECIVE_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_TICKET_RECIVE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CHANNEL", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<OrdOrderOP> getOrdOrderList(@Param("pageNo") Long pageNo, @Param("prePageCount") Long prePageCount, @Param("initUserId") Long initUserId);

    @Select({
            "select",
            "ORDER_ID, ORDER_NO, LOTTO_INST_ID, INIT_USER_ID, DEAL_USER_ID, DEAL_SHOP_ID, ",
            "BET_TIMES, ORDER_TOTAL_BETS_COUNT, ORDER_PRICE, ORDER_STS,COM_GAME_STYLE, TICKET_UPLOAD_STS, ",
            "BONUS_STS, BONUS_AMT, BONUS_DESC,BONUS_PAY_ORDER_NO, ORDER_CREATE_TIME, ORDER_CANCEL_TIME, ORDER_SEND_TIME, ",
            "ORDER_ACCEPT_TIME, ORDER_TICKET_PIC, SUBMIT_FORM_ID, ORDER_PUSHMSG_STS, TICKET_UPLOAD_TIME, ",
            "PAY_ORDER_ID, PAY_CHANNEL, PAY_STS, ORDER_PAY_TIME, ORDER_REJECT_TIME,ORDER_SOURCE, CHASE_NO, ",
            "COP_ORDER_NO, RECIVE_BONUS_TIME, RECIVE_BONUS_STS_TIME, APPLY_BONUS_TIME, FINISH_BONUS_TIME,",
            "ORDER_TICKET_RECIVE_STS, ORDER_TICKET_RECIVE_TIME,ORDER_CHANNEL ",
            "from t_ord_order",
            "where INIT_USER_ID = #{initUserId,jdbcType=BIGINT} and BONUS_STS in ('B','S')",
            "order by ORDER_CREATE_TIME desc",
            "LIMIT  #{pageNo,jdbcType=BIGINT},#{prePageCount,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
            @Arg(column="ORDER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
            @Arg(column="ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="LOTTO_INST_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="INIT_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_SHOP_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BET_TIMES", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_TOTAL_BETS_COUNT", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_PRICE", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="COM_GAME_STYLE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="TICKET_UPLOAD_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_AMT", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BONUS_DESC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="BONUS_PAY_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_CREATE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CANCEL_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SEND_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_ACCEPT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_PIC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="SUBMIT_FORM_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_PUSHMSG_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="TICKET_UPLOAD_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="PAY_ORDER_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="PAY_CHANNEL", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="PAY_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_PAY_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_REJECT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SOURCE", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="CHASE_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="COP_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="RECIVE_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="RECIVE_BONUS_STS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="APPLY_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="FINISH_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_RECIVE_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_TICKET_RECIVE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CHANNEL", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<OrdOrderOP> getUserWinOrdOrderList(@Param("pageNo") Long pageNo, @Param("prePageCount") Long prePageCount, @Param("initUserId") Long initUserId);

    @Select({
            "select",
            "ORDER_ID, ORDER_NO, LOTTO_INST_ID, INIT_USER_ID, DEAL_USER_ID, DEAL_SHOP_ID, ",
            "BET_TIMES, ORDER_TOTAL_BETS_COUNT, ORDER_PRICE, ORDER_STS,COM_GAME_STYLE, TICKET_UPLOAD_STS, ",
            "BONUS_STS, BONUS_AMT, BONUS_DESC,BONUS_PAY_ORDER_NO, ORDER_CREATE_TIME, ORDER_CANCEL_TIME, ORDER_SEND_TIME, ",
            "ORDER_ACCEPT_TIME, ORDER_TICKET_PIC, SUBMIT_FORM_ID, ORDER_PUSHMSG_STS, TICKET_UPLOAD_TIME, ",
            "PAY_ORDER_ID, PAY_CHANNEL, PAY_STS, ORDER_PAY_TIME,ORDER_REJECT_TIME, ORDER_SOURCE, CHASE_NO, ",
            "COP_ORDER_NO, RECIVE_BONUS_TIME, RECIVE_BONUS_STS_TIME, APPLY_BONUS_TIME, FINISH_BONUS_TIME,",
            "ORDER_TICKET_RECIVE_STS, ORDER_TICKET_RECIVE_TIME,ORDER_CHANNEL ",
            "from t_ord_order",
            "where DEAL_SHOP_ID = #{shopId,jdbcType=BIGINT} and ORDER_STS = #{orderSts,jdbcType=CHAR}",
            "order by ORDER_CREATE_TIME desc",
            "LIMIT  #{pageNo,jdbcType=BIGINT},#{prePageCount,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
            @Arg(column="ORDER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
            @Arg(column="ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="LOTTO_INST_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="INIT_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_SHOP_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BET_TIMES", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_TOTAL_BETS_COUNT", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_PRICE", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="COM_GAME_STYLE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="TICKET_UPLOAD_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_AMT", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BONUS_DESC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="BONUS_PAY_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_CREATE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CANCEL_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SEND_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_ACCEPT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_PIC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="SUBMIT_FORM_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_PUSHMSG_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="TICKET_UPLOAD_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="PAY_ORDER_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="PAY_CHANNEL", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="PAY_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_PAY_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_REJECT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SOURCE", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="CHASE_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="COP_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="RECIVE_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="RECIVE_BONUS_STS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="APPLY_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="FINISH_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_RECIVE_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_TICKET_RECIVE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CHANNEL", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<OrdOrderOP> queryShopOrderList(@Param("pageNo") Long pageNo, @Param("prePageCount") Long prePageCount,  @Param("shopId") Long shopId,@Param("orderSts") String orderSts);



    @Select({
            "select",
            "ORDER_ID, ORDER_NO, LOTTO_INST_ID, INIT_USER_ID, DEAL_USER_ID, DEAL_SHOP_ID, ",
            "BET_TIMES, ORDER_TOTAL_BETS_COUNT, ORDER_PRICE, ORDER_STS,COM_GAME_STYLE, TICKET_UPLOAD_STS, ",
            "BONUS_STS, BONUS_AMT, BONUS_DESC,BONUS_PAY_ORDER_NO, ORDER_CREATE_TIME, ORDER_CANCEL_TIME, ORDER_SEND_TIME, ",
            "ORDER_ACCEPT_TIME, ORDER_TICKET_PIC, SUBMIT_FORM_ID, ORDER_PUSHMSG_STS, TICKET_UPLOAD_TIME, ",
            "PAY_ORDER_ID, PAY_CHANNEL, PAY_STS, ORDER_PAY_TIME,ORDER_REJECT_TIME, ORDER_SOURCE, CHASE_NO, ",
            "COP_ORDER_NO, RECIVE_BONUS_TIME, RECIVE_BONUS_STS_TIME, APPLY_BONUS_TIME, FINISH_BONUS_TIME,",
            "ORDER_TICKET_RECIVE_STS, ORDER_TICKET_RECIVE_TIME,ORDER_CHANNEL ",
            "from t_ord_order",
            "where DEAL_SHOP_ID = #{shopId,jdbcType=BIGINT} and ORDER_STS IN ('A','S','B')",
            "order by ORDER_CREATE_TIME desc",
            "LIMIT  #{pageNo,jdbcType=BIGINT},#{prePageCount,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
            @Arg(column="ORDER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
            @Arg(column="ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="LOTTO_INST_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="INIT_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_SHOP_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BET_TIMES", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_TOTAL_BETS_COUNT", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_PRICE", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="COM_GAME_STYLE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="TICKET_UPLOAD_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_AMT", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BONUS_DESC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="BONUS_PAY_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_CREATE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CANCEL_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SEND_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_ACCEPT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_PIC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="SUBMIT_FORM_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_PUSHMSG_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="TICKET_UPLOAD_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="PAY_ORDER_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="PAY_CHANNEL", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="PAY_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_PAY_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_REJECT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SOURCE", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="CHASE_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="COP_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="RECIVE_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="RECIVE_BONUS_STS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="APPLY_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="FINISH_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_RECIVE_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_TICKET_RECIVE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CHANNEL", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<OrdOrderOP> queryShopDealedOrderList(@Param("pageNo") Long pageNo, @Param("prePageCount") Long prePageCount,  @Param("shopId") Long shopId);


    @Select({
            "select",
            "ORDER_ID, ORDER_NO, LOTTO_INST_ID, INIT_USER_ID, DEAL_USER_ID, DEAL_SHOP_ID, ",
            "BET_TIMES, ORDER_TOTAL_BETS_COUNT, ORDER_PRICE, ORDER_STS,COM_GAME_STYLE, TICKET_UPLOAD_STS, ",
            "BONUS_STS, BONUS_AMT, BONUS_DESC,BONUS_PAY_ORDER_NO, ORDER_CREATE_TIME, ORDER_CANCEL_TIME, ORDER_SEND_TIME, ",
            "ORDER_ACCEPT_TIME, ORDER_TICKET_PIC, SUBMIT_FORM_ID, ORDER_PUSHMSG_STS, TICKET_UPLOAD_TIME, ",
            "PAY_ORDER_ID, PAY_CHANNEL, PAY_STS, ORDER_PAY_TIME,ORDER_REJECT_TIME, ORDER_SOURCE, CHASE_NO, ",
            "COP_ORDER_NO, RECIVE_BONUS_TIME, RECIVE_BONUS_STS_TIME, APPLY_BONUS_TIME, FINISH_BONUS_TIME,",
            "ORDER_TICKET_RECIVE_STS, ORDER_TICKET_RECIVE_TIME,ORDER_CHANNEL ",
            "from t_ord_order",
            "where DEAL_SHOP_ID = #{shopId,jdbcType=BIGINT} and ORDER_STS IN ('P','W')",
            "order by ORDER_CREATE_TIME desc",
            "LIMIT  #{pageNo,jdbcType=BIGINT},#{prePageCount,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
            @Arg(column="ORDER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
            @Arg(column="ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="LOTTO_INST_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="INIT_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_SHOP_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BET_TIMES", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_TOTAL_BETS_COUNT", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_PRICE", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="COM_GAME_STYLE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="TICKET_UPLOAD_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_AMT", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BONUS_DESC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="BONUS_PAY_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_CREATE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CANCEL_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SEND_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_ACCEPT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_PIC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="SUBMIT_FORM_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_PUSHMSG_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="TICKET_UPLOAD_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="PAY_ORDER_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="PAY_CHANNEL", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="PAY_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_PAY_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_REJECT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SOURCE", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="CHASE_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="COP_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="RECIVE_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="RECIVE_BONUS_STS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="APPLY_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="FINISH_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_RECIVE_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_TICKET_RECIVE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CHANNEL", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<OrdOrderOP> queryShopUnDealedOrderList(@Param("pageNo") Long pageNo, @Param("prePageCount") Long prePageCount,  @Param("shopId") Long shopId);

    @Select({
            "select",
            "ORDER_ID, ORDER_NO, LOTTO_INST_ID, INIT_USER_ID, DEAL_USER_ID, DEAL_SHOP_ID, ",
            "BET_TIMES, ORDER_TOTAL_BETS_COUNT, ORDER_PRICE, ORDER_STS,COM_GAME_STYLE, TICKET_UPLOAD_STS, ",
            "BONUS_STS, BONUS_AMT, BONUS_DESC,BONUS_PAY_ORDER_NO, ORDER_CREATE_TIME, ORDER_CANCEL_TIME, ORDER_SEND_TIME, ",
            "ORDER_ACCEPT_TIME, ORDER_TICKET_PIC, SUBMIT_FORM_ID, ORDER_PUSHMSG_STS, TICKET_UPLOAD_TIME, ",
            "PAY_ORDER_ID, PAY_CHANNEL, PAY_STS, ORDER_PAY_TIME,ORDER_REJECT_TIME, ORDER_SOURCE, CHASE_NO, ",
            "COP_ORDER_NO, RECIVE_BONUS_TIME, RECIVE_BONUS_STS_TIME, APPLY_BONUS_TIME, FINISH_BONUS_TIME,",
            "ORDER_TICKET_RECIVE_STS, ORDER_TICKET_RECIVE_TIME,ORDER_CHANNEL ",
            "from t_ord_order",
            "where DEAL_SHOP_ID = #{shopId,jdbcType=BIGINT} and BONUS_STS = #{bonusSts,jdbcType=VARCHAR}",
            "order by ORDER_CREATE_TIME desc",
            "LIMIT  #{pageNo,jdbcType=BIGINT},#{prePageCount,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
            @Arg(column="ORDER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
            @Arg(column="ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="LOTTO_INST_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="INIT_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_SHOP_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BET_TIMES", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_TOTAL_BETS_COUNT", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_PRICE", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="COM_GAME_STYLE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="TICKET_UPLOAD_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_AMT", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BONUS_DESC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="BONUS_PAY_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_CREATE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CANCEL_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SEND_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_ACCEPT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_PIC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="SUBMIT_FORM_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_PUSHMSG_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="TICKET_UPLOAD_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="PAY_ORDER_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="PAY_CHANNEL", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="PAY_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_PAY_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_REJECT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SOURCE", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="CHASE_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="COP_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="RECIVE_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="RECIVE_BONUS_STS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="APPLY_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="FINISH_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_RECIVE_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_TICKET_RECIVE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CHANNEL", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<OrdOrderOP> queryShopBonusList(@Param("bonusSts") String bonusSts,@Param("pageNo") Long pageNo, @Param("prePageCount") Long prePageCount, @Param("shopId") Long shopId);

    @Select("<script>"
            + "select "
            + "ORDER_ID, ORDER_NO, a.LOTTO_INST_ID, INIT_USER_ID, DEAL_USER_ID, DEAL_SHOP_ID, "
            + "BET_TIMES, ORDER_TOTAL_BETS_COUNT, ORDER_PRICE, ORDER_STS,COM_GAME_STYLE, TICKET_UPLOAD_STS, "
            + "BONUS_STS, BONUS_AMT, BONUS_DESC,BONUS_PAY_ORDER_NO, ORDER_CREATE_TIME, ORDER_CANCEL_TIME, ORDER_SEND_TIME, "
            + "ORDER_ACCEPT_TIME, ORDER_TICKET_PIC, SUBMIT_FORM_ID, ORDER_PUSHMSG_STS, TICKET_UPLOAD_TIME, "
            + "PAY_ORDER_ID, PAY_CHANNEL, PAY_STS, ORDER_PAY_TIME, ORDER_REJECT_TIME,ORDER_SOURCE, CHASE_NO, "
            + "COP_ORDER_NO, RECIVE_BONUS_TIME, RECIVE_BONUS_STS_TIME, APPLY_BONUS_TIME, FINISH_BONUS_TIME, "
            + "ORDER_TICKET_RECIVE_STS, ORDER_TICKET_RECIVE_TIME,ORDER_CHANNEL "
            + "from t_ord_order a,t_lot_inst b,t_lot_lotto c "
            + "where ORDER_STS IN "
            + "<foreach item='orderSts' index='index' collection='orderSts' open='(' separator=',' close=')'>"
            + " #{orderSts} "
            + "</foreach>"
            + " AND a.DEAL_SHOP_ID IS NOT NULL AND a.ORDER_CHANNEL IN ('LOTTO_STORE_MP','ZDJL_MP') AND a.LOTTO_INST_ID = b.LOTTO_INST_ID AND b.PERIOD_STS = 'E' AND b.LOTTO_ID = c.LOTTO_ID AND c.LOTTO_TYPE IN "
            + "<foreach item='lottoType' index='index' collection='lottoType' open='(' separator=',' close=')'>"
            + " #{lottoType}"
            + "</foreach>"
            + "</script>")
    @ConstructorArgs({
            @Arg(column="ORDER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
            @Arg(column="ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="LOTTO_INST_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="INIT_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_SHOP_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BET_TIMES", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_TOTAL_BETS_COUNT", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_PRICE", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="COM_GAME_STYLE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="TICKET_UPLOAD_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_AMT", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BONUS_DESC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="BONUS_PAY_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_CREATE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CANCEL_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SEND_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_ACCEPT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_PIC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="SUBMIT_FORM_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_PUSHMSG_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="TICKET_UPLOAD_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="PAY_ORDER_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="PAY_CHANNEL", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="PAY_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_PAY_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_REJECT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SOURCE", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="CHASE_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="COP_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="RECIVE_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="RECIVE_BONUS_STS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="APPLY_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="FINISH_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_RECIVE_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_TICKET_RECIVE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CHANNEL", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<OrdOrderOP> selectNeedBonusCheckOrder(@Param("orderSts") String[] orderSts,@Param("lottoType") String[] lottoType);



    @Select({
            "select",
            "ORDER_ID, ORDER_NO, LOTTO_INST_ID, INIT_USER_ID, DEAL_USER_ID, DEAL_SHOP_ID, ",
            "BET_TIMES, ORDER_TOTAL_BETS_COUNT, ORDER_PRICE, ORDER_STS,COM_GAME_STYLE, TICKET_UPLOAD_STS, ",
            "BONUS_STS, BONUS_AMT, BONUS_DESC,BONUS_PAY_ORDER_NO, ORDER_CREATE_TIME, ORDER_CANCEL_TIME, ORDER_SEND_TIME, ",
            "ORDER_ACCEPT_TIME, ORDER_TICKET_PIC, SUBMIT_FORM_ID, ORDER_PUSHMSG_STS, TICKET_UPLOAD_TIME, ",
            "PAY_ORDER_ID, PAY_CHANNEL, PAY_STS, ORDER_PAY_TIME,ORDER_REJECT_TIME, ORDER_SOURCE, CHASE_NO, ",
            "COP_ORDER_NO, RECIVE_BONUS_TIME, RECIVE_BONUS_STS_TIME, APPLY_BONUS_TIME, FINISH_BONUS_TIME,",
            "ORDER_TICKET_RECIVE_STS, ORDER_TICKET_RECIVE_TIME,ORDER_CHANNEL ",
            "from t_ord_order",
            "where DEAL_SHOP_ID IS NOT NULL AND ORDER_STS = 'I' AND DATE_ADD(ORDER_CREATE_TIME,interval 1 hour)<NOW()",
            "order by ORDER_CREATE_TIME desc"
    })
    @ConstructorArgs({
            @Arg(column="ORDER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
            @Arg(column="ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="LOTTO_INST_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="INIT_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_SHOP_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BET_TIMES", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_TOTAL_BETS_COUNT", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_PRICE", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="COM_GAME_STYLE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="TICKET_UPLOAD_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_AMT", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BONUS_DESC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="BONUS_PAY_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_CREATE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CANCEL_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SEND_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_ACCEPT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_PIC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="SUBMIT_FORM_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_PUSHMSG_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="TICKET_UPLOAD_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="PAY_ORDER_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="PAY_CHANNEL", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="PAY_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_PAY_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_REJECT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SOURCE", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="CHASE_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="COP_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="RECIVE_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="RECIVE_BONUS_STS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="APPLY_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="FINISH_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_RECIVE_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_TICKET_RECIVE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CHANNEL", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<OrdOrderOP> queryOutOfTimePayOrder();

    @Update({
            "update t_ord_order ",
            "set ORDER_STS = 'N', ",
            "ORDER_CANCEL_TIME = NOW() ",
            "where DEAL_SHOP_ID IS NOT NULL AND ORDER_STS = 'I' AND DATE_ADD(ORDER_CREATE_TIME,interval 1 hour)<NOW()"
    })
    int updateOutOfTimePayOrder();



    @Select({
            "select",
            "ORDER_ID, ORDER_NO, LOTTO_INST_ID, INIT_USER_ID, DEAL_USER_ID, DEAL_SHOP_ID, ",
            "BET_TIMES, ORDER_TOTAL_BETS_COUNT, ORDER_PRICE, ORDER_STS,COM_GAME_STYLE, TICKET_UPLOAD_STS, ",
            "BONUS_STS, BONUS_AMT, BONUS_DESC,BONUS_PAY_ORDER_NO, ORDER_CREATE_TIME, ORDER_CANCEL_TIME, ORDER_SEND_TIME, ",
            "ORDER_ACCEPT_TIME, ORDER_TICKET_PIC, SUBMIT_FORM_ID, ORDER_PUSHMSG_STS, TICKET_UPLOAD_TIME, ",
            "PAY_ORDER_ID, PAY_CHANNEL, PAY_STS, ORDER_PAY_TIME,ORDER_REJECT_TIME, ORDER_SOURCE, CHASE_NO, ",
            "COP_ORDER_NO, RECIVE_BONUS_TIME, RECIVE_BONUS_STS_TIME, APPLY_BONUS_TIME, FINISH_BONUS_TIME,",
            "ORDER_TICKET_RECIVE_STS, ORDER_TICKET_RECIVE_TIME,ORDER_CHANNEL ",
            "from t_ord_order",
            "where DEAL_SHOP_ID IS NOT NULL AND ORDER_STS = 'P' AND DATE_ADD(ORDER_CREATE_TIME,interval 24 hour)<NOW()",
            "order by ORDER_CREATE_TIME desc"
    })
    @ConstructorArgs({
            @Arg(column="ORDER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
            @Arg(column="ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="LOTTO_INST_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="INIT_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_USER_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="DEAL_SHOP_ID", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BET_TIMES", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_TOTAL_BETS_COUNT", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_PRICE", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
            @Arg(column="ORDER_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="COM_GAME_STYLE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="TICKET_UPLOAD_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="BONUS_AMT", javaType=Long.class, jdbcType=JdbcType.BIGINT),
            @Arg(column="BONUS_DESC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="BONUS_PAY_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_CREATE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CANCEL_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SEND_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_ACCEPT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_PIC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="SUBMIT_FORM_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="ORDER_PUSHMSG_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="TICKET_UPLOAD_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="PAY_ORDER_ID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="PAY_CHANNEL", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="PAY_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_PAY_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_REJECT_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_SOURCE", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="CHASE_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="COP_ORDER_NO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
            @Arg(column="RECIVE_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="RECIVE_BONUS_STS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="APPLY_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="FINISH_BONUS_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_TICKET_RECIVE_STS", javaType=String.class, jdbcType=JdbcType.CHAR),
            @Arg(column="ORDER_TICKET_RECIVE_TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
            @Arg(column="ORDER_CHANNEL", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<OrdOrderOP> queryOutOfTimeDealOrder();

}